---
- hosts: loadbalancer
  become: true
  tasks:
    - name: verify loadbalancer status 
      command: service nginx status 

    - name: verify nginx listens on port 80
      wait_for: port=80 timeout=1

- hosts: database
  become: true
  tasks:
    - name: verify database status 
      command: service mysql status 

    - name: verify mysql listens on port 3306
      wait_for: port=3306 timeout=1

- hosts: webserver
  become: true
  tasks:
    - name: verify web servers status 
      command: service apache2 status 

    - name: verify apache listens on port 80
      wait_for: port=80 timeout=1      

- hosts: control
  tasks: 
    - name: verify end-to-end reponse
      uri: url=http://{{item}} return_content=yes
      with_items: "{{ groups.loadbalancer }}"
      register: lb_index 

    - fail: msg="index failed to return content"
      when: "'Hello, from sunny' not in item.content"
      with_items: "{{ lb_index.results }}"

- hosts: loadbalancer
  tasks: 
    - name: verify web end-to-end reponse
      uri: url=http://{{item}} return_content=yes
      with_items: "{{ groups.webserver }}"
      register: app_index 

    - fail: msg="index failed to return content"
      when: "'Hello, from sunny {{item.item.split('.')[0]}}' not in item.content"
      with_items: "{{ app_index.results }}"

- hosts: loadbalancer
  tasks: 
    - name: verify db end-to-end reponse
      uri: url=http://{{item}}/db return_content=yes
      with_items: "{{ groups.webserver }}"
      register: app_index 

    - fail: msg="db failed to return content"
      when: "'Database Connected from {{item.item.split('.')[0]}}' not in item.content"
      with_items: "{{ app_index.results }}"
