---
# Bring stack down
- hosts: loadbalancer
  become: true
  gather_facts: false
  tasks:
    - service: name=nginx state=stopped
    - wait_for: port=80 state=drained
  tags: ['service']

- hosts: webserver
  become: true
  gather_facts: false
  tasks:
    - service: name=apache2 state=stopped
    - wait_for: port=80 state=stopped
  tags: ['service']
      

# Restart mysql
- hosts: database
  become: true
  gather_facts: false
  tasks:
    - service: name=mysql state=restarted
    - wait_for: port=3306 state=started
  tags: ['service']

# Bring stack up
- hosts: webserver
  become: true
  gather_facts: false
  tasks:
    - service: name=apache2 state=started
    - wait_for: port=80
  tags: ['service']

- hosts: loadbalancer
  become: true
  gather_facts: false
  tasks:
    - service: name=nginx state=started
    - wait_for: port=80
  tags: ['service']
