---
- name: install webserver requirements
  apt: name={{item}} state=present
  with_items: 
    - apache2
    - libapache2-mod-wsgi
  tags: ['packages']

- name: de-activate default apache site 
  file: path=/etc/apache2/sites-enabled/000-default.conf state=absent
  notify: apache2 restart 
  tags: ['configure']
  
- name: ensure webserver service started
  service: name=apache2 state=started enabled=yes
  tags: ['service']