---
- hosts: webserver
  become: true
  roles:
    - apache2
    - role: demo_app
      # demo_app takes the common variables from group_vars
      db_username: "{{ db_user_name }}"
      db_userpass: "{{ db_user_pass }}"
