---
- hosts: webserver
  become: true
  tasks: 

    #- name: stop nginx service started
    #  service: name=nginx state=stopped enabled=no

    #- name: remove nginx dependencies 
    #  apt: name={{item}} state=removed 
    #  with_items:
        # - nginx-core
        # - libnginx-mod-http-geoip
        # - libnginx-mod-http-image-filter
        # - libnginx-mod-http-xslt-filter
        # - libnginx-mod-mail
        # - libnginx-mod-stream
        # - nginx-common

    # - name: install webserver requirements
    #   apt: name={{item}} state=present update_cache=yes
    #   with_items: 
    #     - apache2
    #     - libapache2-mod-wsgi
    #     - python-pip
    #     - python-virtualenv
    #     - python-mysqldb

    # - name: ensure webserver service started
    #   service: name=apache2 state=started enabled=yes

    - name: check wsgi module enabled 
      apache2_module: state=present name=wsgi 
      notify: apache2 restart 
    
    - name: copy demo virtual site config 
      copy: src=../demo/demo.conf dest=/etc/apache2/sites-available mode=0755
      notify: apache2 restart 

    - name: copy website data 
      copy: src=../demo/app/ dest=/var/www/demo mode=0755
      notify: apache2 restart 
    
    - name: setup python virtual environment 
      pip: requirements=/var/www/demo/requirements.txt virtualenv=/var/www/demo/.venv 
      notify: apache2 restart 

    - name: de-activate default apache site 
      file: path=/etc/apache2/sites-enabled/000-default.conf state=absent
      notify: apache2 restart 

    - name: activate demo apache site 
      file: src=/etc/apache2/sites-available/demo.conf dest=/etc/apache2/sites-enabled/demo.conf state=link
      notify: apache2 restart 

  handlers:
    - name: apache2 restart 
      service: name=apache2 state=restarted